export const platforms = [
    {
        name: "BeOS",
        icon: "k_beos.gif",
        slug: "beos",
    },
    {
        name: "Linux",
        icon: "k_linux.gif",
        slug: "linux",
    },
    {
        name: "MS-Dos",
        icon: "k_msdos.gif",
        slug: "msdos",
    },
    {
        name: "Windows",
        icon: "k_win.gif",
        slug: "windows",
    },
    {
        name: "MS-Dos/gus",
        icon: "k_gus.gif",
        slug: "msdosgus",
    },
    {
        name: "Atari ST",
        icon: "k_atari_st.gif",
        slug: "atarist",
    },
    {
        name: "Amiga AGA",
        icon: "k_amiga_aga.gif",
        slug: "amigaaga",
    },
    {
        name: "Atari STe",
        icon: "k_atari_ste.gif",
        slug: "atariste",
    },
    {
        name: "Amiga OCS/ECS",
        icon: "k_amiga.gif",
        slug: "amigaocsecs",
    },
    {
        name: "Java",
        icon: "k_java.gif",
        slug: "java",
    },
    {
        name: "Playstation",
        icon: "k_ps1.gif",
        slug: "playstation",
    },
    {
        name: "Commodore 64",
        icon: "k_commodore.gif",
        slug: "commodore64",
    },
    {
        name: "Wild",
        icon: "k_wild.gif",
        slug: "wild",
    },
    {
        name: "Amstrad CPC",
        icon: "k_cpc.gif",
        slug: "amstradcpc",
    },
    {
        name: "Amiga PPC/RTG",
        icon: "k_amiga_ppc.gif",
        slug: "amigappcrtg",
    },
    {
        name: "Atari Falcon 030",
        icon: "k_atari_falcon.gif",
        slug: "atarifalcon030",
    },
    {
        name: "Gameboy",
        icon: "k_gameboy.gif",
        slug: "gameboy",
    },
    {
        name: "ZX Spectrum",
        icon: "k_zx.gif",
        slug: "zxspectrum",
    },
    {
        name: "MacOSX PPC",
        icon: "k_macb.gif",
        slug: "macosxppc",
    },
    {
        name: "MacOS",
        icon: "k_mac.gif",
        slug: "macos",
    },
    {
        name: "Gameboy Advance",
        icon: "k_gba.gif",
        slug: "gameboyadvance",
    },
    {
        name: "Gameboy Color",
        icon: "k_gbc.gif",
        slug: "gameboycolor",
    },
    {
        name: "Dreamcast",
        icon: "k_dreamcast.gif",
        slug: "dreamcast",
    },
    {
        name: "SNES/Super Famicom",
        icon: "k_snes.gif",
        slug: "snessuperfamicom",
    },
    {
        name: "SEGA Genesis/Mega Drive",
        icon: "k_megadrive.gif",
        slug: "segagenesismegadrive",
    },
    {
        name: "Flash",
        icon: "k_flash.gif",
        slug: "flash",
    },
    {
        name: "Oric",
        icon: "k_oric.gif",
        slug: "oric",
    },
    {
        name: "Mobile Phone",
        icon: "k_mobiles.gif",
        slug: "mobilephone",
    },
    {
        name: "VIC 20",
        icon: "k_vic20.gif",
        slug: "vic20",
    },
    {
        name: "Playstation 2",
        icon: "k_ps2.gif",
        slug: "playstation2",
    },
    {
        name: "TI-8x (68k)",
        icon: "k_ti8x.gif",
        slug: "ti8x68k",
    },
    {
        name: "Atari TT 030",
        icon: "k_tt.gif",
        slug: "ataritt030",
    },
    {
        name: "Acorn",
        icon: "k_acorn.gif",
        slug: "acorn",
    },
    {
        name: "JavaScript",
        icon: "k_js.gif",
        slug: "javascript",
    },
    {
        name: "Alambik",
        icon: "k_alambik.gif",
        slug: "alambik",
    },
    {
        name: "NEC TurboGrafx/PC Engine",
        icon: "k_pce.gif",
        slug: "necturbografxpcengine",
    },
    {
        name: "XBOX",
        icon: "k_xbox.gif",
        slug: "xbox",
    },
    {
        name: "PalmOS",
        icon: "k_palmos.gif",
        slug: "palmos",
    },
    {
        name: "Nintendo 64",
        icon: "k_n64.gif",
        slug: "nintendo64",
    },
    {
        name: "C16/116/plus4",
        icon: "k_c16.gif",
        slug: "c16116plus4",
    },
    {
        name: "PocketPC",
        icon: "k_pocketpc.gif",
        slug: "pocketpc",
    },
    {
        name: "PHP",
        icon: "k_php.gif",
        slug: "php",
    },
    {
        name: "MSX",
        icon: "k_msx.gif",
        slug: "msx",
    },
    {
        name: "GamePark GP32",
        icon: "k_gamepark32.gif",
        slug: "gameparkgp32",
    },
    {
        name: "Atari XL/XE",
        icon: "k_atari_xl_xe.gif",
        slug: "atarixlxe",
    },
    {
        name: "Intellivision",
        icon: "k_intellivision.gif",
        slug: "intellivision",
    },
    {
        name: "Thomson",
        icon: "k_thomson.gif",
        slug: "thomson",
    },
    {
        name: "Apple II GS",
        icon: "k_iigs.gif",
        slug: "appleiigs",
    },
    {
        name: "SEGA Master System",
        icon: "k_mastersystem.gif",
        slug: "segamastersystem",
    },
    {
        name: "NES/Famicom",
        icon: "k_nes.gif",
        slug: "nesfamicom",
    },
    {
        name: "Gamecube",
        icon: "k_ngc.gif",
        slug: "gamecube",
    },
    {
        name: "GamePark GP2X",
        icon: "k_gp2x.gif",
        slug: "gameparkgp2x",
    },
    {
        name: "Atari VCS",
        icon: "k_atari_vcs.gif",
        slug: "atarivcs",
    },
    {
        name: "Virtual Boy",
        icon: "k_vb.gif",
        slug: "virtualboy",
    },
    {
        name: "BK-0010/11M",
        icon: "k_bk.gif",
        slug: "bk001011m",
    },
    {
        name: "Pokemon Mini",
        icon: "k_pokemon.gif",
        slug: "pokemonmini",
    },
    {
        name: "SEGA Game Gear",
        icon: "k_gg.gif",
        slug: "segagamegear",
    },
    {
        name: "Vectrex",
        icon: "k_vectrex.gif",
        slug: "vectrex",
    },
    {
        name: "iOS",
        icon: "k_ipod.gif",
        slug: "ios",
    },
    {
        name: "Playstation Portable",
        icon: "k_psp.gif",
        slug: "playstationportable",
    },
    {
        name: "Nintendo DS",
        icon: "k_ds.gif",
        slug: "nintendods",
    },
    {
        name: "Atari Jaguar",
        icon: "k_jag.gif",
        slug: "atarijaguar",
    },
    {
        name: "Wonderswan",
        icon: "k_wonderswan.gif",
        slug: "wonderswan",
    },
    {
        name: "NeoGeo Pocket",
        icon: "k_neogeopocket.gif",
        slug: "neogeopocket",
    },
    {
        name: "XBOX 360",
        icon: "k_xbox360.gif",
        slug: "xbox360",
    },
    {
        name: "Atari Lynx",
        icon: "k_lynx.gif",
        slug: "atarilynx",
    },
    {
        name: "C64 DTV",
        icon: "k_dtv.gif",
        slug: "c64dtv",
    },
    {
        name: "Amstrad Plus",
        icon: "k_amplus.gif",
        slug: "amstradplus",
    },
    {
        name: "FreeBSD",
        icon: "k_freebsd.gif",
        slug: "freebsd",
    },
    {
        name: "Solaris",
        icon: "k_solaris.gif",
        slug: "solaris",
    },
    {
        name: "Spectravideo 3x8",
        icon: "k_sv.gif",
        slug: "spectravideo3x8",
    },
    {
        name: "Apple II",
        icon: "k_apple2.gif",
        slug: "appleii",
    },
    {
        name: "MacOSX Intel",
        icon: "k_macosx.gif",
        slug: "macosxintel",
    },
    {
        name: "Playstation 3",
        icon: "k_ps3.gif",
        slug: "playstation3",
    },
    {
        name: "Nintendo Wii",
        icon: "k_wii.gif",
        slug: "nintendowii",
    },
    {
        name: "SGI/IRIX",
        icon: "k_sgi.gif",
        slug: "sgiirix",
    },
    {
        name: "BBC Micro",
        icon: "k_bbcmicro.gif",
        slug: "bbcmicro",
    },
    {
        name: "MSX 2",
        icon: "k_msx2.gif",
        slug: "msx2",
    },
    {
        name: "SAM Coup\u00e9",
        icon: "k_samcoupe.gif",
        slug: "samcoup",
    },
    {
        name: "TRS-80/CoCo",
        icon: "k_coco.gif",
        slug: "trs80coco",
    },
    {
        name: "MSX Turbo-R",
        icon: "k_msxt.gif",
        slug: "msxturbor",
    },
    {
        name: "Enterprise",
        icon: "k_ent.gif",
        slug: "enterprise",
    },
    {
        name: "MSX 2 plus",
        icon: "k_msx2p.gif",
        slug: "msx2plus",
    },
    {
        name: "ZX-81",
        icon: "k_zx81.gif",
        slug: "zx81",
    },
    {
        name: "Android",
        icon: "k_android.gif",
        slug: "android",
    },
    {
        name: "mIRC",
        icon: "k_mirc.gif",
        slug: "mirc",
    },
    {
        name: "Commodore 128",
        icon: "k_c128.gif",
        slug: "commodore128",
    },
    {
        name: "Raspberry Pi",
        icon: "k_raspi.gif",
        slug: "raspberrypi",
    },
    {
        name: "Sharp MZ",
        icon: "k_sharpmz.gif",
        slug: "sharpmz",
    },
    {
        name: "ZX Enhanced",
        icon: "k_zxenhanced.gif",
        slug: "zxenhanced",
    },
    {
        name: "Animation/Video",
        icon: "k_video.gif",
        slug: "animationvideo",
    },
    {
        name: "PICO-8",
        icon: "k_pico8.png",
        slug: "pico8",
    },
    {
        name: "TI-8x (Z80)",
        icon: "k_tiz80.gif",
        slug: "ti8xz80",
    },
    {
        name: "TIC-80",
        icon: "k_tic80.png",
        slug: "tic80",
    },
];

export const types = [
    "32b",
    "64b",
    "128b",
    "256b",
    "512b",
    "1k",
    "4k",
    "8k",
    "16k",
    "32k",
    "40k",
    "64k",
    "80k",
    "96k",
    "100k",
    "128k",
    "256k",
    "artpack",
    "bbstro",
    "cracktro",
    "demo",
    "demopack",
    "demotool",
    "dentro",
    "diskmag",
    "fastdemo",
    "game",
    "intro",
    "invitation",
    "liveact",
    "musicdisk",
    "procedural graphics",
    "report",
    "slideshow",
    "votedisk",
    "wild",
];
